// src/pages/AdminDashboard.jsx
import React, { useEffect, useState } from 'react';
import { supabase } from '../lib/supabaseClient';
import { useAuth } from '../context/AuthContext';
import MindTrackLogo from '../components/MindTrackLogo';
import { NavIcons, DashboardIcons } from '../components/MoodVectors';

const AdminDashboard = () => {
  const { user } = useAuth();
  
  // Navigation layout tab switches: 'flags' | 'verifications' | 'pairings'
  const [activeTab, setActiveTab] = useState('flags');
  const [loading, setLoading] = useState(true);

  // Data storage arrays (Synced to live database schemas)
  const [verificationRequests, setVerificationRequests] = useState([]);
  const [criticalFlags, setCriticalFlags] = useState([]);
  const [activePairings, setActivePairings] = useState([]);
  const [verifiedProfessionals, setVerifiedProfessionals] = useState([]);

  // Assignment interface state machine hooks
  const [selectedFlag, setSelectedFlag] = useState(null);
  const [targetProfessionalId, setTargetProfessionalId] = useState('');
  const [isSubmittingAssignment, setIsSubmittingAssignment] = useState(false);

  // --- COMPONENT DATA FETCHING MODULES ---
  
  // Tab A Logic: Fetch active critical flags generated by backend thresholds
  const fetchCriticalSystemFlags = async () => {
    try {
      const { data, error } = await supabase
        .from('notifications')
        .select('*')
        .eq('notification_type', 'alert')
        .eq('severity_level', 'high')
        .eq('is_read', false);

      if (error) throw error;
      setCriticalFlags(data || []);
    } catch (err) {
      console.error('Error fetching system critical indicators:', err.message);
    }
  };

  // Tab B Logic: Integrated verification auditing engine (Your provided backend core)
  const fetchPendingVerifications = async () => {
    try {
      const { data, error } = await supabase
        .from('verification_requests')
        .select(`
          id, profession_type, license_number, status, created_at, professional_id, document_url,
          profile ( full_name )
        `)
        .eq('status', 'pending');

      if (error) throw error;
      setVerificationRequests(data || []);
    } catch (err) {
      console.error('Error fetching system audit payloads:', err.message);
    }
  };

  // Tab C Logic: Fetch the trace map log ledger showing multi-role care handshakes
  const fetchActiveCarePairings = async () => {
    try {
      const { data, error } = await supabase
        .from('access_requests')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;
      setActivePairings(data || []);
    } catch (err) {
      console.error('Error fetching active pairing ledger fields:', err.message);
    }
  };

  // Dropdown Utility: Query approved practitioners to populate the assignment form select box
  const fetchApprovedPractitionersList = async () => {
    try {
      const { data, error } = await supabase
        .from('verification_requests')
        .select(`professional_id, profile ( full_name, id )`)
        .eq('status', 'approved');

      if (error) throw error;
      
      if (data && data.length > 0) {
        setVerifiedProfessionals(data.map(item => ({
          id: item.professional_id,
          name: item.profile?.full_name || 'Verified Professional'
        })));
      } else {
        // Presentation Fallback: Seed your project teammates if database queries return empty
        setVerifiedProfessionals([
          { id: 'prof-azlina-utem', name: 'Dr. Azlina (UTeM Health Sciences)' },
          { id: 'prof-sakinah-utem', name: 'Dr. Sakinah (Melaka Center)' },
          { id: 'prof-alya-utem', name: 'Dr. Alya (Hospital Alor Gajah)' }
        ]);
      }
    } catch (err) {
      console.error('Error building practitioners registry map:', err.message);
    }
  };

  const synchronizeMasterAdminData = async () => {
    setLoading(true);
    await Promise.all([
      fetchCriticalSystemFlags(),
      fetchPendingVerifications(),
      fetchActiveCarePairings(),
      fetchApprovedPractitionersList()
    ]);
    setLoading(false);
  };

  useEffect(() => {
    if (user) {
      synchronizeMasterAdminData();
    }
  }, [user]);

  // --- INTERACTIVE ACTION TRANSACTION HANDLERS ---

  // Action B Handler: Process licensing audits (Your original verified transaction link)
  const handleVerifyPractitionerLicense = async (requestId, statusOutcome) => {
    try {
      const { error } = await supabase
        .from('verification_requests')
        .update({ status: statusOutcome })
        .eq('id', requestId);

      if (error) throw error;
      alert(`Account application registry has been successfully ${statusOutcome}.`);
      synchronizeMasterAdminData();
    } catch (err) {
      alert('Audit submission failed: ' + err.message);
    }
  };

  // Action A Handler: Deploy the complete assignment and dispatch user notice channels
  const handleExecuteCareAssignment = async (e) => {
    e.preventDefault();
    if (!targetProfessionalId) {
      alert('Please isolate an approved clinical care node.');
      return;
    }
    setIsSubmittingAssignment(true);

    try {
      const targetDoctor = verifiedProfessionals.find(p => p.id === targetProfessionalId);

      // Step A: Insert a record tracking entry into public.access_requests
      const { data: requestRow, error: requestErr } = await supabase
        .from('access_requests')
        .insert([{
          admin_id: user.id,
          user_id: selectedFlag.profile_id,
          professional_id: targetProfessionalId,
          user_agreed: false,
          professional_agreed: false,
          status: 'assigned'
        }])
        .select().single();

      if (requestErr) throw requestErr;

      // Step B: Dispatch the alert to the flagged student's notification system inbox
      const { error: noticeErr } = await supabase
        .from('notifications')
        .insert([{
          profile_id: selectedFlag.profile_id,
          notification_type: 'request',
          title: 'Practitioner Assignment Consent Request',
          message: `Administrative Action: ${targetDoctor.name} has been assigned to view your historical tracking trends charts. Please authorize access tokens inside your notification panel.`,
          severity_level: 'medium',
          is_read: false,
          request_id: requestRow.id
        }]);

      if (noticeErr) throw noticeErr;

      // Step C: Resolve the active system alert flag so it clears from the dashboard view
      await supabase
        .from('notifications')
        .update({ is_read: true })
        .eq('id', selectedFlag.id);

      alert('Care tracking assignment transaction initialized successfully.');
      setSelectedFlag(null);
      setTargetProfessionalId('');
      synchronizeMasterAdminData();
    } catch (err) {
      alert('Transaction failure: ' + err.message);
    } finally {
      setIsSubmittingAssignment(false);
    }
  };

  // Helper utility to parse doctor parameters inside the auditing grid list map
  const resolvePractitionerIdentityText = (idString) => {
    const match = verifiedProfessionals.find(p => p.id === idString);
    return match ? match.name : 'Assigned Care Practitioner';
  };

  return (
    <div className="dashboard-layout">
      {/* SIDEBAR NAVIGATION BLOCK */}
      <aside className="sidebar-nav">
        <div className="sidebar-brand-box"><MindTrackLogo showText={true} /></div>
        <div style={{ padding: '12px 24px', fontSize: '11px', fontWeight: 700, color: '#9a8c98', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Admin Panel</div>
        <ul className="sidebar-menu-links">
          <li className={`sidebar-link-item ${activeTab === 'flags' ? 'active' : ''}`} onClick={() => setActiveTab('flags')}>
            <NavIcons.History /><span>Critical System Flags</span>
          </li>
          <li className={`sidebar-link-item ${activeTab === 'verifications' ? 'active' : ''}`} onClick={() => setActiveTab('verifications')}>
            <NavIcons.AddEntry /><span>Practitioner Audits</span>
          </li>
          <li className={`sidebar-link-item ${activeTab === 'pairings' ? 'active' : ''}`} onClick={() => setActiveTab('pairings')}>
            <NavIcons.Analytics /><span>Care Token Auditing</span>
          </li>
          <li className="sidebar-link-item" onClick={() => supabase.auth.signOut()} style={{ marginTop: 'auto', color: '#e53e3e' }}>
            🚪 <span>Sign Out Session</span>
          </li>
        </ul>
      </aside>

      {/* MAIN VIEW SCREEN VIEWPORT CONTROLLER */}
      <div className="dashboard-main-content">
        <nav className="top-navbar">
          <div className="nav-left-cluster"><span className="user-greeting">Administrative Governance Console</span></div>
          <span className="status-pill-badge approved">Secure Server Linked</span>
        </nav>

        <main className="workspace-view">
          {loading ? (
            <p style={{ textAlign: 'center', color: '#8d99ae', padding: '40px' }}>Syncing secure administrative data arrays...</p>
          ) : (
            <>
              {/* VIEW TAB A: CRITICAL ANOMALIES & ASSIGNMENT FLAGS */}
              {activeTab === 'flags' && (
                <div>
                  <div className="workspace-header">
                    <div>
                      <h2 style={{ marginBottom: '4px' }}>Critical Care Response Center</h2>
                      <p style={{ color: '#8d99ae', margin: 0, fontSize: '14px' }}>Students flagged dynamically by the rules engine following sustained score drops under 45%.</p>
                    </div>
                  </div>

                  <div className="notification-list-deck">
                    {criticalFlags.length === 0 ? (
                      <div style={{ textAlign: 'center', background: '#ffffff', padding: '40px', borderRadius: '14px', border: '1px solid #e9ecef', color: '#8d99ae' }}>
                        No untriaged student distress flags require immediate care routing.
                      </div>
                    ) : (
                      criticalFlags.map((flag) => (
                        <div key={flag.id} className="notification-card-item" style={{ borderLeft: '5px solid #e53e3e' }}>
                          <div className="notification-left-block">
                            <div className="notification-bell-icon-frame alert-style">⚠️</div>
                            <div className="notification-text-details">
                              <h4>Automatic Low-Wellness Boundary Flag Triggered</h4>
                              <p style={{ margin: '4px 0', fontSize: '13px' }}><strong>Student Target Profile ID:</strong> {flag.profile_id || 'W-Member'}</p>
                              <p style={{ color: '#6c757d', fontStyle: 'italic' }}>"{flag.message}"</p>
                              <span className="notification-timestamp-tag">Trapped: {new Date(flag.created_at).toLocaleString()}</span>
                            </div>
                          </div>
                          <div className="notification-actions-grid">
                            <button className="btn-action-approve" onClick={() => setSelectedFlag(flag)}>
                              Assign Practitioner
                            </button>
                          </div>
                        </div>
                      ))
                    )}
                  </div>
                </div>
              )}

              {/* VIEW TAB B: PRACTITIONER LICENSE VERIFICATIONS */}
              {activeTab === 'verifications' && (
                <div className="analytics-chart-card">
                  <h4 className="analytics-chart-title">📋 Pending Professional Application Audits</h4>
                  {verificationRequests.length === 0 ? (
                    <p style={{ color: '#8d99ae', textAlign: 'center', padding: '20px', margin: 0, fontStyle: 'italic' }}>
                      No professional license registrations require administrative validation at this time.
                    </p>
                  ) : (
                    <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: '10px' }}>
                      <thead>
                        <tr style={{ textAlign: 'left', borderBottom: '2px solid #e9ecef', color: '#9a8c98', fontSize: '13px' }}>
                          <th style={{ padding: '12px' }}>Applicant Name</th>
                          <th>Specialty Field</th>
                          <th>License Number</th>
                          <th>Credential File</th>
                          <th style={{ textAlign: 'center' }}>Actions Ledger</th>
                        </tr>
                      </thead>
                      <tbody>
                        {verificationRequests.map((req) => {
                          const nameStr = req.profile?.full_name || 'Practitioner Candidate';
                          return (
                            <tr key={req.id} style={{ borderBottom: '1px solid #f4f6f8', fontSize: '13.5px' }}>
                              <td style={{ padding: '15px 12px', fontWeight: '600' }}>{nameStr}</td>
                              <td>{req.profession_type}</td>
                              <td style={{ fontFamily: 'monospace', color: '#e07a5f', fontWeight: '600' }}>{req.license_number}</td>
                              <td>
                                {req.document_url ? (
                                  <a href={req.document_url} target="_blank" rel="noopener noreferrer" style={{ color: '#81b29a', fontWeight: '700', textDecoration: 'underline' }}>
                                    View Certificate Asset
                                  </a>
                                ) : <span style={{ color: '#8d99ae' }}>No Document attached</span>}
                              </td>
                              <td style={{ display: 'flex', gap: '8px', justifyContent: 'center', padding: '15px 12px' }}>
                                <button onClick={() => handleVerifyPractitionerLicense(req.id, 'approved')} className="btn-action-approve" style={{ padding: '6px 12px', fontSize: '12.5px' }}>
                                  Approve Professional
                                </button>
                                <button onClick={() => handleVerifyPractitionerLicense(req.id, 'rejected')} className="btn-action-decline" style={{ padding: '6px 12px', fontSize: '12.5px' }}>
                                  Reject
                                </button>
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  )}
                </div>
              )}

              {/* VIEW TAB C: MASTER ACCESS LEDGER AUDITING */}
              {activeTab === 'pairings' && (
                <div>
                  <div className="workspace-header">
                    <div>
                      <h2 style={{ marginBottom: '4px' }}>Care Token Access Ledger Map</h2>
                      <p style={{ color: '#8d99ae', margin: 0, fontSize: '14px' }}>Trace history ledger showing the live mutual consent statuses of active practitioner monitoring request variables.</p>
                    </div>
                  </div>

                  <div className="history-list-wrapper">
                    {activePairings.length === 0 ? (
                      <div style={{ textAlign: 'center', background: '#ffffff', padding: '40px', borderRadius: '14px', border: '1px solid #e9ecef', color: '#8d99ae' }}>
                        No care assignments have been mapped within the system records yet.
                      </div>
                    ) : (
                      activePairings.map((pair) => (
                        <div key={pair.id} className="history-item-card">
                          <div className="history-card-left-section">
                            <div className="history-metadata-box">
                              <h4 className="history-date-header">Student Tracker: <span style={{ color: '#4F46E5' }}>{pair.user_id}</span></h4>
                              <p style={{ margin: '6px 0 4px 0', fontSize: '13.5px' }}>
                                🩺 <strong>Assigned Practitioner:</strong> {resolvePractitionerIdentityText(pair.professional_id)}
                              </p>
                              <div className="history-activity-pills-row" style={{ marginTop: '8px', display: 'flex', gap: '8px' }}>
                                <span className={`history-pill-tag ${pair.user_agreed ? 'sleep' : 'study'}`}>
                                  User Handshake: {pair.user_agreed ? 'AUTHORIZED' : 'PENDING'}
                                </span>
                                <span className={`history-pill-tag ${pair.professional_agreed ? 'exercise' : 'study'}`}>
                                  Practitioner Intake: {pair.professional_agreed ? 'ACCEPTED' : 'PENDING'}
                                </span>
                              </div>
                            </div>
                          </div>
                          <div className="history-card-actions-cluster">
                            <span className={`status-pill-badge ${pair.status === 'active' ? 'approved' : 'rejected'}`}>
                              {pair.status}
                            </span>
                          </div>
                        </div>
                      ))
                    )}
                  </div>
                </div>
              )}
            </>
          )}
        </main>
      </div>

      {/* OVERLAY INTERACTIVE ASSIGNMENT FORM FORM */}
      {selectedFlag && (
        <div className="modal-backdrop-layer">
          <div className="modal-content-card">
            <div className="modal-header-row">
              <h3>Secure Care Assignment Token</h3>
              <button className="close-modal-x" onClick={() => setSelectedFlag(null)}>×</button>
            </div>

            <div className="modal-notes-block" style={{ backgroundColor: '#fff5f5', borderLeftColor: '#e53e3e', fontSize: '13px' }}>
              <strong>Flagged Student Profile Target:</strong> {selectedFlag.profile_id}
            </div>

            <form onSubmit={handleExecuteCareAssignment}>
              <div className="form-input-container" style={{ display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '16px' }}>
                <label style={{ fontSize: '13.5px', fontWeight: 700 }}>Select Approved Clinical Professional Node:</label>
                <select 
                  className="filter-select-dropdown"
                  style={{ width: '100%', padding: '12px', boxSizing: 'border-box' }}
                  value={targetProfessionalId}
                  onChange={e => setTargetProfessionalId(e.target.value)}
                  required
                >
                  <option value="">-- Choose Professional Personnel --</option>
                  {verifiedProfessionals.map(prof => (
                    <option key={prof.id} value={prof.id}>{prof.name}</option>
                  ))}
                </select>
              </div>

              <div style={{ display: 'flex', gap: '12px', marginTop: '28px' }}>
                <button type="submit" className="modal-action-btn-primary" style={{ flex: 2, margin: 0 }} disabled={isSubmittingAssignment}>
                  {isSubmittingAssignment ? 'Syncing Handshake Ledger...' : 'Deploy Care Assignment'}
                </button>
                <button type="button" className="modal-action-btn-secondary" style={{ flex: 1 }} onClick={() => setSelectedFlag(null)}>
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default AdminDashboard;